version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  postgresql:
    networks:
      - app-tier
    image: postgres:13
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      TZ: "Asia/Seoul"
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    restart: always
    ports:
      - "3000:3000"
    links:
      - postgresql
    depends_on:
      - postgresql
